### ISSUE TITLE
Some `Sigma.Windows.Hayabusa.Rule` rules does not detect logs(`Hayabusa v2.5.0` and `Velociraptor v0.72`)

### ISSUE THREAD

**Issue by fukusuket** [Velocidex/velociraptor-sigma-rules#30]
Hello :)
Since the `Hayabusa Ruleset` were recently updated, I compared the results of `Hayabusa` and `Velociraptor Sigma plugin`.

I would appreciate it if you could check it out.
Thank you!

#### Hayabusa
- [Hayabusa v2.15.0](https://github.com/Yamato-Security/hayabusa/releases/tag/v2.15.0)
  - `hayabusa-2.15.0-win-x64.exe json-timeline -l -o timeline.json -w -D -n -u`
    - Above option's description(I think that the Velociraptor Hayabusa Ruleset probably does not exclude the following rules.)
      - `-D`, --enable-deprecated-rules         Enable rules with a status of deprecated
      - `-n`, --enable-noisy-rules              Enable rules set to noisy (./rules/config/noisy_rules.txt
      - `-u`, --enable-unsupported-rules        Enable rules with a status of unsupported

#### Velociraptor
- [velociraptor-v0.72.0-windows-amd64.exe](https://github.com/Velocidex/velociraptor/releases/tag/v0.72)
  - RuleLevel: All
  - RuleStatus: All Rules 

### Detection result diff
The following rules are detected by `Hayabusa`, but not by `Velociraptor Sigma plugin`.
The following rules can be searched at [This site](https://sigma.velocidex.com/docs/artifacts/velociraptor_hayabusa_event_ruleset/), so I think they are included in the rule set. Is my understanding correct?
|No|Rule|Detected Log|
|--|--|--|
|1|[BITS Transfer Job With Uncommon Or Suspicious Remote TLD](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/bits_client/win_bits_client_new_transfer_via_uncommon_tld.yml)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080399031|
|2|[CodeIntegrity - Unmet Signing Level Requirements By File Under Validation](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/code_integrity/win_codeintegrity_attempted_dll_load.yml#L1)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080399290|
|3| [Credential Manager Accessed](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerAccessed.yml#L5)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080399643|
|4| [Credential Manager Enumerated](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerEnumerated.yml#L5)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080402092|
|5| [Device Conn](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Partition_Diagnostic/PartitionDiagnostic_1006_Info_DeviceConn.yml#L5)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080402202|
|6| [MSI Installation From Suspicious Locations](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml#L1)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080402212|
|7| [Microsoft Defender Blocked from Loading Unsigned DLL](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/security_mitigations/win_security_mitigations_defender_load_unsigned_dll.yml#L1)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080402223|
|8| [Microsoft Defender Tamper Protection Trigger](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/windefend/win_defender_tamper_protection_trigger.yml#L1)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080402231|
|9| [Office App PopUp](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/OAlerts/OAlerts_300_Info_OfficeAppPopUp.yml#L5)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080403640|
|10| [RDP Attempt](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/TerminalServices-RDPClient_Op/RDP-Client_1102_Info_ConnAttempt.yml#L5)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080403663|
|11|[RDP Conn Attempt](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/TerminalServices-RDPClient_Op/RDP-Client_1024_Info_ConnAttempt.yml#L5)|https://github.com/Velocidex/velociraptor-sigma-rules/issues/30#issuecomment-2080403684|

**Comment by fukusuket** [comment]
### [BITS Transfer Job With Uncommon Or Suspicious Remote TLD](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/bits_client/win_bits_client_new_transfer_via_uncommon_tld.yml)
#### hayabusa's detected event log(json)
```json
{
    "Timestamp": "2024-03-31 08:00:54.876 +09:00",
    "RuleTitle": "BITS Transfer Job With Uncommon Or Suspicious Remote TLD",
    "Level": "med",
    "Computer": "mouse",
    "Channel": "BitsCli",
    "EventID": 16403,
    "RecordID": 7602,
    "Details": {
    },
    "ExtraFieldInfo": {
        "ClientProcessStartKey": 20547673299883310,
        "LocalName": "C:\\Windows\\TEMP\\v64_16.0.17328.20184CheckReachableDE4BF1F9-5DB1-43E9-B2D7-57B8C82E0BA4",
        "RemoteName": "http://f.c2r.ts.cdn.office.net/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/Office/Data/v64_16.0.17328.20184.cab",
        "User": "NT AUTHORITY\\SYSTEM",
        "fileCount": 1,
        "jobId": "58DD3DA8-D6AF-4B7F-85BF-42968B4466CF",
        "jobOwner": "NT AUTHORITY\\SYSTEM",
        "jobTitle": "Microsoft Office Click-to-Run",
        "processId": 11848
    }
}
```

**Comment by fukusuket** [comment]
### [CodeIntegrity - Unmet Signing Level Requirements By File Under Validation](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/sigma/builtin/code_integrity/win_codeintegrity_attempted_dll_load.yml#L1)

#### hayabusa's detected event log(json)
```json
{
    "Timestamp": "2023-10-21 09:06:25.095 +09:00",
    "RuleTitle": "CodeIntegrity - Unmet Signing Level Requirements By File Under Validation",
    "Level": "low",
    "Computer": "mouse",
    "Channel": "CodeInteg",
    "EventID": 3033,
    "RecordID": 11909,
    "Details": {
    },
    "ExtraFieldInfo": {
        "FileNameBuffer": "\\Device\\HarddiskVolume3\\Program Files\\McAfee\\WPS\\1.11.279.1\\mc-sec-plugin-x64.dll",
        "FileNameLength": 81,
        "ProcessNameBuffer": "\\Device\\HarddiskVolume3\\Windows\\System32\\svchost.exe",
        "ProcessNameLength": 52,
        "RequestedPolicy": 12,
        "Status": 3221226536,
        "ValidatedPolicy": 1
    }
}
```

**Comment by fukusuket** [comment]
#### [Credential Manager Accessed](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerAccessed.yml#L5)
#### hayabusa's detected event log(json)
```json
{
    "Timestamp": "2024-03-30 13:19:38.030 +09:00",
    "RuleTitle": "Credential Manager Accessed",
    "Level": "low",
    "Computer": "mouse",
    "Channel": "Sec",
    "EventID": 5379,
    "RecordID": 291312,
    "Details": {
        "PID": 14476,
        "SrcUser": "fukus",
        "Tgt": "MicrosoftAccount:user=fukusuke.takahashi@gmail.com",
        "CredsReturned": 1,
        "ReturnCode": 0,
        "LID": "0xba35ae3",
        "SrcSID": "S-1-5-21-2349003748-4255172932-178375392-1002"
    },
    "ExtraFieldInfo": {
        "ProcessCreationTime": "2024-03-30T04:19:36.747978Z",
        "ReadOperation": "%%8099",
        "SubjectDomainName": "MOUSE"
    }
}
```

**Comment by fukusuket** [comment]
#### [Credential Manager Enumerated](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerEnumerated.yml#L5)
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### [Credential Manager Enumerated](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerEnumerated.yml#L5)
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### [Credential Manager Enumerated](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerEnumerated.yml#L5)
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### [Credential Manager Enumerated](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerEnumerated.yml#L5)
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### [Credential Manager Enumerated](https://github.com/Yamato-Security/hayabusa-rules/blob/00ef978f5a6a0235fdee17021b3aa3e356160ffc/hayabusa/builtin/Security/Default/Sec_5397_Low_CredentialManagerEnumerated.yml#L5)
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### No.9 
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### No.10 
#### hayabusa's detected event log(json)
```json
```

**Comment by fukusuket** [comment]
#### No.11 
#### hayabusa's detected event log(json)
```json
```

**Comment by scudette** [comment]
Thanks for testing and reporting this!

These rules were rejected as you can see here https://github.com/Velocidex/velociraptor-sigma-rules/actions/runs/8852698892/job/24321831550#step:6:223 because I have not updated the field mapping for them yet.

I just synced the Hayabusa git repo but did not spend the time to understand the new schema changes. I will look into it now.

**Comment by fukusuket** [comment]
@scudette  
Thank you so much for checking :)  If there's anything we can do to help with testing or impl, please let us know. I'll be happy to test it.

**Comment by scudette** [comment]
Thanks for testing it and reporting!

I submitted a change which allows us:

1. Automatically build field mapping in the trivial case where a rule uses fields which are known to be in a particular log source (These were mainly the changes since the last sync)
2. Mark bad rules so they do not count towards failing the compile.

There are quite a number of bad rules in the Hayabusa set and this compiler tries to reject them and warn. Previously this was not an error just a warning that the rule was rejected but now with the ability to mark the rule as bad we can ignore it and be more particular on detecting new rules which fail.

This way we can work towards making it an error for a rule to fail so next time I do a sync it is obvious which rules need adjustment.

**Comment by scudette** [comment]
the latest change records the rejected rules and their reason so we can keep track of them with git. This should help flag new breakages as we sync the rules with upstream.

You can see the Hayabusa rules that were rejected here
https://github.com/Velocidex/velociraptor-sigma-rules/blob/master/rejected/windows_hayabusa_rejects.json

the reasons vary from invalid yaml to undefined fields and invalid modifiers. We also do not currently support Timeframe and aggregate rules so we reject those too.

Thanks again for testing and reporting these issues!
